# Generated by Django 3.2.8 on 2021-10-09 14:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('makers', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='application',
            name='postion',
            field=models.CharField(choices=[('REQUESTED', 'requested for participation'), ('MEMBER', 'member'), ('ADMIN', 'admin who has permissions')], default='REQUESTED', max_length=10),
        ),
        migrations.AlterField(
            model_name='application',
            name='progress_status',
            field=models.CharField(choices=[('WAITING', 'wating for open'), ('IN_PROGRESS', 'project is working on it'), ('DONE', 'project is done')], default='WAITING', max_length=20),
        ),
    ]
