# Generated by Django 4.0 on 2021-12-14 12:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('makers', '0002_auto_20211009_1443'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='application',
            name='progress_status',
        ),
        migrations.AddField(
            model_name='group',
            name='progress_status',
            field=models.CharField(choices=[('WAITING', 'wating for open'), ('IN_PROGRESS', 'project is working on it'), ('DONE', 'project is done')], default='WAITING', max_length=20),
        ),
    ]
